<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produk = [
            // ==================== SAYURAN (Kategori 1) ====================
            [
                'id_petani' => 2, // Pak Tono
                'id_kategori' => 1,
                'nama_produk' => 'Wortel Organik Premium',
                'slug_produk' => 'wortel-organik-premium',
                'harga' => 15000.00,
                'stok' => 100,
                'stok_direserve' => 5,
                'satuan' => 'kg',
                'deskripsi' => 'Wortel organik segar dari dataran tinggi Bogor. Dipanen langsung dari kebun tanpa pestisida. Kaya vitamin A dan serat, cocok untuk jus, salad, atau masakan sehari-hari.',
                'foto' => 'produk/wortel_organik.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 1,
                'nama_produk' => 'Bayam Hijau Segar',
                'slug_produk' => 'bayam-hijau-segar',
                'harga' => 8000.00,
                'stok' => 50,
                'stok_direserve' => 0,
                'satuan' => 'ikat',
                'deskripsi' => 'Bayam hijau organik, dipetik pagi hari untuk menjaga kesegaran. Kaya zat besi dan vitamin K. Ideal untuk tumis, sup, atau salad.',
                'foto' => 'produk/bayam_hijau.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 1,
                'nama_produk' => 'Kangkung Hidroponik',
                'slug_produk' => 'kangkung-hidroponik',
                'harga' => 10000.00,
                'stok' => 80,
                'stok_direserve' => 3,
                'satuan' => 'ikat',
                'deskripsi' => 'Kangkung hidroponik berkualitas tinggi. Lebih bersih dan bebas hama. Batang renyah dan daun segar.',
                'foto' => 'produk/kangkung_hidroponik.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 1,
                'nama_produk' => 'Brokoli Organik',
                'slug_produk' => 'brokoli-organik',
                'harga' => 25000.00,
                'stok' => 30,
                'stok_direserve' => 2,
                'satuan' => 'kg',
                'deskripsi' => 'Brokoli organik segar dari dataran tinggi. Kaya antioksidan dan vitamin C. Cocok untuk tumis, sup, atau dikukus.',
                'foto' => 'produk/brokoli_organik.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 1,
                'nama_produk' => 'Cabai Merah Keriting',
                'slug_produk' => 'cabai-merah-keriting',
                'harga' => 45000.00,
                'stok' => 25,
                'stok_direserve' => 0,
                'satuan' => 'kg',
                'deskripsi' => 'Cabai merah keriting segar dengan tingkat kepedasan sedang. Cocok untuk sambal dan masakan pedas.',
                'foto' => 'produk/cabai_merah.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 1,
                'nama_produk' => 'Selada Romaine',
                'slug_produk' => 'selada-romaine',
                'harga' => 12000.00,
                'stok' => 40,
                'stok_direserve' => 0,
                'satuan' => 'pcs',
                'deskripsi' => 'Selada romaine hidroponik, renyah dan segar. Perfect untuk salad Caesar atau sandwich.',
                'foto' => 'produk/selada_romaine.png',
                'is_aktif' => true,
            ],

            // ==================== BUAH (Kategori 2) ====================
            [
                'id_petani' => 2,
                'id_kategori' => 2,
                'nama_produk' => 'Tomat Cherry Merah',
                'slug_produk' => 'tomat-cherry-merah',
                'harga' => 35000.00,
                'stok' => 45,
                'stok_direserve' => 5,
                'satuan' => 'kg',
                'deskripsi' => 'Tomat cherry merah manis, cocok untuk salad atau snack sehat. Kaya lycopene dan vitamin C.',
                'foto' => 'produk/tomat_cherry.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 2,
                'nama_produk' => 'Apel Malang Premium',
                'slug_produk' => 'apel-malang-premium',
                'harga' => 28000.00,
                'stok' => 60,
                'stok_direserve' => 10,
                'satuan' => 'kg',
                'deskripsi' => 'Apel Malang asli, manis dan renyah. Dipetik langsung dari kebun di lereng Gunung Bromo.',
                'foto' => 'produk/apel_malang.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 2,
                'nama_produk' => 'Jeruk Pontianak',
                'slug_produk' => 'jeruk-pontianak',
                'harga' => 22000.00,
                'stok' => 75,
                'stok_direserve' => 0,
                'satuan' => 'kg',
                'deskripsi' => 'Jeruk Pontianak manis tanpa biji. Kaya vitamin C, cocok untuk jus atau dimakan langsung.',
                'foto' => 'produk/jeruk_pontianak.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 2,
                'nama_produk' => 'Pepaya California',
                'slug_produk' => 'pepaya-california',
                'harga' => 18000.00,
                'stok' => 35,
                'stok_direserve' => 0,
                'satuan' => 'kg',
                'deskripsi' => 'Pepaya California orange, manis dan lembut. Cocok untuk dessert atau jus.',
                'foto' => 'produk/pepaya_california.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 2,
                'nama_produk' => 'Pisang Cavendish',
                'slug_produk' => 'pisang-cavendish',
                'harga' => 20000.00,
                'stok' => 50,
                'stok_direserve' => 8,
                'satuan' => 'sisir',
                'deskripsi' => 'Pisang Cavendish grade A, manis dan tidak cepat busuk. Ideal untuk snack sehat atau smoothie.',
                'foto' => 'produk/pisang_cavendish.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 2,
                'nama_produk' => 'Semangka Merah',
                'slug_produk' => 'semangka-merah',
                'harga' => 25000.00,
                'stok' => 20,
                'stok_direserve' => 0,
                'satuan' => 'buah',
                'deskripsi' => 'Semangka merah tanpa biji, manis dan segar. Berat rata-rata 3-4 kg per buah.',
                'foto' => 'produk/semangka_merah.png',
                'is_aktif' => true,
            ],

            // ==================== TANAMAN HIAS (Kategori 3) ====================
            [
                'id_petani' => 3,
                'id_kategori' => 3,
                'nama_produk' => 'Monstera Deliciosa',
                'slug_produk' => 'monstera-deliciosa',
                'harga' => 175000.00,
                'stok' => 15,
                'stok_direserve' => 2,
                'satuan' => 'pot',
                'deskripsi' => 'Monstera Deliciosa dengan daun berlubang cantik. Tinggi 40-50cm dengan pot diameter 20cm. Indoor plant favorit!',
                'foto' => 'produk/monstera_deliciosa.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 3,
                'nama_produk' => 'Calathea Makoyana',
                'slug_produk' => 'calathea-makoyana',
                'harga' => 85000.00,
                'stok' => 20,
                'stok_direserve' => 0,
                'satuan' => 'pot',
                'deskripsi' => 'Calathea Makoyana dengan motif daun unik seperti lukisan. Prayer plant yang bergerak mengikuti cahaya.',
                'foto' => 'produk/calathea_makoyana.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 3,
                'nama_produk' => 'Philodendron Birkin',
                'slug_produk' => 'philodendron-birkin',
                'harga' => 125000.00,
                'stok' => 12,
                'stok_direserve' => 1,
                'satuan' => 'pot',
                'deskripsi' => 'Philodendron Birkin dengan garis-garis putih elegan pada daun hijau. Tanaman hias premium.',
                'foto' => 'produk/philodendron_birkin.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 3,
                'nama_produk' => 'Alocasia Black Velvet',
                'slug_produk' => 'alocasia-black-velvet',
                'harga' => 150000.00,
                'stok' => 8,
                'stok_direserve' => 0,
                'satuan' => 'pot',
                'deskripsi' => 'Alocasia Black Velvet dengan daun hitam beludru dan urat putih. Tanaman eksotis collector item.',
                'foto' => 'produk/alocasia_black_velvet.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 3,
                'nama_produk' => 'Sansevieria Moonshine',
                'slug_produk' => 'sansevieria-moonshine',
                'harga' => 65000.00,
                'stok' => 25,
                'stok_direserve' => 3,
                'satuan' => 'pot',
                'deskripsi' => 'Sansevieria Moonshine dengan daun silver-green. Low maintenance, cocok untuk pemula.',
                'foto' => 'produk/sansevieria_moonshine.png',
                'is_aktif' => true,
            ],

            // ==================== BIBIT (Kategori 4) ====================
            [
                'id_petani' => 2,
                'id_kategori' => 4,
                'nama_produk' => 'Bibit Cabai Rawit',
                'slug_produk' => 'bibit-cabai-rawit',
                'harga' => 5000.00,
                'stok' => 200,
                'stok_direserve' => 15,
                'satuan' => 'pack',
                'deskripsi' => 'Bibit cabai rawit unggul, 1 pack berisi 20 biji. Tingkat perkecambahan 85%. Siap tanam dalam polybag.',
                'foto' => 'produk/bibit_cabai_rawit.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 4,
                'nama_produk' => 'Bibit Tomat Cherry',
                'slug_produk' => 'bibit-tomat-cherry',
                'harga' => 7500.00,
                'stok' => 150,
                'stok_direserve' => 0,
                'satuan' => 'pack',
                'deskripsi' => 'Bibit tomat cherry premium, 1 pack berisi 15 biji. Varietas produktif dengan buah manis.',
                'foto' => 'produk/bibit_tomat_cherry.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 4,
                'nama_produk' => 'Bibit Terong Ungu',
                'slug_produk' => 'bibit-terong-ungu',
                'harga' => 6000.00,
                'stok' => 120,
                'stok_direserve' => 5,
                'satuan' => 'pack',
                'deskripsi' => 'Bibit terong ungu lokal, 1 pack berisi 25 biji. Hasil panen melimpah dan tahan hama.',
                'foto' => 'produk/bibit_terong_ungu.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 4,
                'nama_produk' => 'Bibit Bayam Hijau',
                'slug_produk' => 'bibit-bayam-hijau',
                'harga' => 3500.00,
                'stok' => 250,
                'stok_direserve' => 10,
                'satuan' => 'pack',
                'deskripsi' => 'Bibit bayam hijau organik, 1 pack berisi 50 biji. Cepat tumbuh, panen dalam 25-30 hari.',
                'foto' => 'produk/bibit_bayam_hijau.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 4,
                'nama_produk' => 'Bibit Kangkung',
                'slug_produk' => 'bibit-kangkung',
                'harga' => 3000.00,
                'stok' => 300,
                'stok_direserve' => 0,
                'satuan' => 'pack',
                'deskripsi' => 'Bibit kangkung darat premium, 1 pack berisi 50 biji. Mudah ditanam di pot atau lahan terbuka.',
                'foto' => 'produk/bibit_kangkung.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 4,
                'nama_produk' => 'Bibit Selada Keriting',
                'slug_produk' => 'bibit-selada-keriting',
                'harga' => 8000.00,
                'stok' => 100,
                'stok_direserve' => 0,
                'satuan' => 'pack',
                'deskripsi' => 'Bibit selada keriting hidroponik, 1 pack berisi 30 biji. Cocok untuk sistem NFT atau DFT.',
                'foto' => 'produk/bibit_selada_keriting.png',
                'is_aktif' => true,
            ],

            // ==================== PRODUK TAMBAHAN ====================
            [
                'id_petani' => 2,
                'id_kategori' => 1,
                'nama_produk' => 'Sawi Hijau Organik',
                'slug_produk' => 'sawi-hijau-organik',
                'harga' => 9000.00,
                'stok' => 0, // Out of stock
                'stok_direserve' => 0,
                'satuan' => 'ikat',
                'deskripsi' => 'Sawi hijau organik segar, cocok untuk tumis atau sup.',
                'foto' => 'produk/sawi_hijau.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 2,
                'nama_produk' => 'Mangga Harum Manis',
                'slug_produk' => 'mangga-harum-manis',
                'harga' => 32000.00,
                'stok' => 40,
                'stok_direserve' => 5,
                'satuan' => 'kg',
                'deskripsi' => 'Mangga Harum Manis matang pohon, aroma harum dan rasa manis sempurna.',
                'foto' => 'produk/mangga_harum_manis.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 2,
                'id_kategori' => 3,
                'nama_produk' => 'Pothos Golden',
                'slug_produk' => 'pothos-golden',
                'harga' => 35000.00,
                'stok' => 30,
                'stok_direserve' => 0,
                'satuan' => 'pot',
                'deskripsi' => 'Pothos Golden dengan variegasi kuning. Tanaman gantung yang mudah dirawat.',
                'foto' => 'produk/pothos_golden.png',
                'is_aktif' => true,
            ],
            [
                'id_petani' => 3,
                'id_kategori' => 1,
                'nama_produk' => 'Timun Jepang',
                'slug_produk' => 'timun-jepang',
                'harga' => 15000.00,
                'stok' => 55,
                'stok_direserve' => 0,
                'satuan' => 'kg',
                'deskripsi' => 'Timun Jepang segar dan renyah, cocok untuk lalapan atau asinan.',
                'foto' => 'produk/timun_jepang.png',
                'is_aktif' => false, // Nonaktif
            ],
        ];

        foreach ($produk as $item) {
            DB::table('produk')->insertOrIgnore(array_merge($item, [
                'tgl_dibuat' => now(),
                'tgl_update' => now(),
            ]));
        }
    }
}
